services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"     # Default MQTT port
      - "9001:9001"     # Websockets port (optional)
    volumes:
      - ./mosquitto/config:/config
      - ./mosquitto/data:/data
      - ./mosquitto/log:/log
    environment:
      - TZ=America/Detroit
  frigate-listener:
    build: .
    container_name: frigate-listener
#    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./secrets/gcp-key.json:/secrets/gcp-key.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/gcp-key.json
      - MQTT_HOST=mosquitto
    depends_on:
      - mosquitto